### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by neves8232** [Mila432/AFK-Arena-Bot#1]
Hello,
I'm new to python so this might be some dumb questions but yeah, lets start them:
First of all what are the requirements and libraries necessary!
Is this in python 2? cause i've noticed some print errors
For now it's all, if you could "explain" the basics on how to use it, i would appreciate a lot, thanks and keep with the good developing

**Comment by HugoPfeffer** [comment]
I guess it's python3 but I'm also new to python and having a documentation for this script would be nice.

**Comment by wverri** [comment]
Python 2, also couldn't make it work. Getting the following error.

>python main.py
Traceback (most recent call last):
  File "main.py", line 504, in <module>
    a.login_and_collect()
  File "main.py", line 374, in login_and_collect
    self.req_sdk_login(svr_id)
  File "main.py", line 85, in req_sdk_login
    res= self.callAPI(msg.SerializeToString())
  File "main.py", line 355, in callAPI
    self.ws.send_binary(data)
AttributeError: 'API' object has no attribute 'ws'

**Comment by Mila432** [comment]
Python2
